---
- name: Ensure WP-CLI is installed
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0755'

- name: Create WP-CLI configuration directory
  ansible.builtin.file:
    path: /etc/wp-cli
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install WordPress using WP-CLI
  ansible.builtin.command: >
    wp core install
    --url="{{ wp_url }}"
    --title="{{ wp_site_title }}"
    --admin_user="{{ wp_admin_user }}"
    --admin_password="{{ wp_admin_password }}"
    --admin_email="{{ wp_admin_email }}"
  args:
    chdir: "{{ wp_install_dir }}"
  become: false

- name: Ensure WordPress admin user exists and set password (WP-CLI)
  shell: |
    if ! wp user get '{{ wp_admin_user }}' --path={{ wp_install_dir }} --allow-root > /dev/null 2>&1; then
      wp user create '{{ wp_admin_user }}' '{{ wp_admin_email }}' --role=administrator --user_pass='{{ wp_admin_password }}' --path={{ wp_install_dir }} --allow-root
    else
      wp user update '{{ wp_admin_user }}' --user_pass='{{ wp_admin_password }}' --path={{ wp_install_dir }} --allow-root
    fi
  args:
    chdir: "{{ wp_install_dir }}"
  become: false